---
- name: Install pkg generic epel for CentOS
  when: ansible_distribution != "RedHat"
  ansible.builtin.include_tasks:
    file: linux-redhat-software-epel.yml

- name: Install packages generic to rhel
  ansible.builtin.package:
    name: "{{ packages[ansible_os_family].base }}"
    state: present

- name: Instalar software esencial en Redhat/Centos/Oracle
  ansible.builtin.yum:
    name: "{{ packages[ansible_os_family][ansible_distribution_major_version | int] }}"
    state: present

#   when: ansible_distribution_major_version | int == 6
#
# - name: Instalar software esencial en Red Hat/CentOS/Oracle = 7
#   ansible.builtin.yum:
#     name: "{{ linux_redhat7_packages }}"
#     state: present
#   when: ansible_distribution_major_version | int == 7
#
# - name: Instalar software esencial en CentOS/RHEL/Oracle High Version = 8
#   ansible.builtin.dnf:
#     name: "{{ linux_redhat8_packages }}"
#     state: present
#   when: ansible_distribution_major_version | int == 8
#
# - name: Instalar software esencial en CentOS/RHEL/Oracle High Version = 9
#   ansible.builtin.dnf:
#     name: "{{ linux_redhat9_packages }}"
#     state: present
#   when: ansible_distribution_major_version | int == 9
#
# - name: Instalar Server with GUI en RHEL 8-9 / CentOS 8-9 / Oracle 8-9
#   ansible.builtin.command:
#     cmd: dnf groupinstall -y --skip-broken "Server with GUI"
#   register: server_with_gui
#   when:
#     - os_release.split('.')[0] >= '8'
#   changed_when: server_with_gui.rc ! = 0

- name: Remover software innecesario
  ansible.builtin.yum:
    name: libvirt-daemon
    state: absent
