---
- name: Softwarefor amazon
  ansible.builtin.include_tasks:
    file: linux-amazon-software-installation.yml

- name: Instalar software esencial en Amazon 2
  ansible.builtin.package:
    name: "{{ linux_amazon2_packages }}"
    state: present
