---
- name: Install generic rhel software to amazon
  ansible.builtin.package:
    name: "{{ linux_generic_rhel_packages }}"
    state: present

- name: Install generic amazon software to amazon
  ansible.builtin.package:
    name: "{{ linux_generic_amazon_packages }}"
    state: present

- name: Remover software innecesario
  ansible.builtin.yum:
    name: libvirt-daemon
    state: absent
