---
- name: Ajustes SSH
  block:
    - name: Configurar SSH - Deshabilitar consultas DNS
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^UseDNS.*"
        line: "UseDNS no"

    - name: Configurar SSH - Ajustes de keepalive 1
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^ClientAliveInterval"
        line: "ClientAliveInterval 30"

    - name: Change password authentication of no/yes
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?(PasswordAuthentication\\s+)no"
        line: "\\1 yes"

    - name: Configurar SSH - Ajustes de keepalive 2
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^ClientAliveCountMax"
        line: "ClientAliveCountMax 5"

    - name: Validar si la linea existe
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^#?[bB]anner.*"
        state: absent
      check_mode: true
      register: line_ssh_check

    - name: Configurar template de banner SSH
      changed_when: line_ssh_check is changed
      ansible.builtin.template:
        src: templates/ssh_banner.txt.j2
        dest: /etc/ssh/banner.txt
        mode: "0600"

    - name: Configurar SSH - Banner
      changed_when: line_ssh_check is changed
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^Banner.*"
        line: "Banner /etc/ssh/banner.txt"
      notify: reload_sshd

- name: Habilitar Secondary Logging
  block:
    - name: Crear directorio de historial de comandos
      ansible.builtin.file:
        path: /var/log/history
        mode: "01777"
        state: directory

    - name: Asegurarse que exista directorio de scripts
      ansible.builtin.file:
        path: /scripts
        mode: "0750"
        state: directory
        owner: root
        group: root

    - name: Copiar scripts de registro de historial de comandos
      ansible.builtin.template:
        src: "{{ item }}"
        mode: "0750"
        dest: /scripts
      with_items:
        - files/history-log.sh
        - files/compress-history-log.sh

    - name: Configurar cron para comprimir logs de historial de comandos
      ansible.builtin.template:
        src: templates/compress-history-log.cron
        dest: /etc/cron.d
        mode: "0644"

    - name: Configurar registro de historial de comandos en bash de SUSE o Debian/Ubuntu
      ansible.builtin.lineinfile:
        # path: /etc/bash.bashrc
        path: /etc/{{ "bash.bashrc" if ansible_os_family == "Debian" and \
          os_vendor== 'sles' else "bashrc" }}
        state: present
        regexp: '^\. /scripts/history-log.sh'
        line: ". /scripts/history-log.sh"
#      when:
#        os_vendor == 'sles' or
#        os_vendor == 'kali' or
#        ansible_os_family == "Debian"
#
#    - name: Configurar registro de historial de comandos en bash de RedHat/CentOS/Oracle
#      ansible.builtin.lineinfile:
#        path: /etc/bashrc
#        state: present
#        regexp: '^\. /scripts/history-log.sh'
#        line: ". /scripts/history-log.sh"
#      when: ansible_os_family == "RedHat" or
#        os_vendor == 'amazon'
