---
- name: Check for required variables
  ansible.builtin.assert:
    that:
      - pod_network_cidr is defined
      - pod_network_cidr != ""
    quiet: true
    fail_msg: One or more required variables were not defined

- name: Check etcd status
  ansible.builtin.uri:
    url: https://localhost:6443/readyz
    validate_certs: false
    return_content: true
  register: result_check_etcd
  ignore_errors: true

- name: Initialize the cluster
  ansible.builtin.command: kubeadm init --pod-network-cidr {{ pod_network_cidr }} --ignore-preflight-errors=NumCPU --apiserver-cert-extra-sans={{ listen_addr }}
  register: result_k8s_init
  when: result_check_etcd.content != "ok" or result_check_etcd.failed
  changed_when: result_k8s_init.rc != 0
