---
- name: Change shell to my user
  ansible.builtin.shell: |
    set -o pipefail
    usermod -s /usr/bin/fish "{{ os_user }}"
  register: user_fish
  changed_when: user_fish.rc != 0
  args:
    executable: /bin/bash

- name: Change enviroment in rhel
  ansible.builtin.lineinfile:
    path: /etc/environment
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: "^LANG=.*", line: "LANG=en_US.utf-8" }
    - { regexp: "^LC_ALL=.*", line: "LC_ALL=en_US.utf-8" }

- name: Configure the tflint
  ansible.builtin.shell: |
    set -o pipefail
    curl -s "{{ tflint_url }}" | bash
  register: nerd_fonts_1
  changed_when: nerd_fonts_1.rc != 0
  args:
    chdir: /tmp
    executable: /bin/bash

- name: Add value to sudoers file
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    insertafter: 'Defaults\suse_pty'
    line: "Defaults\ttimestamp_type=global"
    validate: /usr/sbin/visudo -cf %s
