---
- name: Up base vars values
  ansible.builtin.include_tasks:
    file: set_values.yml

# Personalice the os with values defect
- name: Personalice the os
  ansible.builtin.include_tasks:
    file: personalice_so.yml

# include task to configure repositories
- name: Configure repositories
  ansible.builtin.include_tasks:
    file: configure_repo.yml

- name: Install packages
  ansible.builtin.include_tasks:
    file: install_programs.yml

- name: Configure firewall in local
  ansible.builtin.include_tasks:
    file: configure_firewall.yml

- name: Configure enviroment with permise of root
  ansible.builtin.include_tasks:
    file: configure_enviroment.yml

- name: Configure Users
  ansible.builtin.include_tasks:
    file: configure_users.yml

- name: Configure servers for autocomplete
  ansible.builtin.include_tasks:
    file: configure_programs.yml

- name: Upgrade SO
  ansible.builtin.apt:
    name: "*"
    state: latest
  notify: Reboot server before uptade
