- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Start cockpit
  when:
    - os_vendor == "rhel"
    - os_maj_release | int > 7
  ansible.builtin.service:
    name: cockpit
    state: started

- name: Reboot if SELinux is changed
  ansible.builtin.reboot:
    reboot_timeout: 3600
  when: selinux_disabled.changed == yes

- name: Execute setupcon
  ansible.builtin.command:
    cmd: setupcon
  register: setupcon_rst
  changed_when: setupcon_rst.rc != 0
