- name: Load values by default
  ansible.builtin.include_role:
    name: ../../ansible_os_basevars

- name: Take the photo preview in remote server
  ansible.builtin.include_role:
    name: ../../../ansible_take_photo

- name: Pause stop by execute reboot
  ansible.builtin.pause:
    prompt: "are you continue"
    echo: true

- name: sanity reboot on server
  when: sanity_reboot == true
  ansible.builtin.reboot:
    reboot_timeout: 300

- name: reboot the server
  reboot:
    reboot_timeout: 300
