---
- name: Pause stop by execute reboot
  ansible.builtin.pause:
    prompt: "are you continue"
    echo: true

- name: Sanity reboot of server
  when: sanity_reboot == true
  ansible.builtin.reboot:
    reboot_timeout: 300

- name: Pause stop by execute reboot
  when: sanity_reboot == true
  ansible.builtin.pause:
    prompt: "are you continue"
    echo: true

- name: Sanity reboot of server
  ansible.builtin.reboot:
    reboot_timeout: 300
